In [1]:
import pandas as pd

data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "Academic Qualification": ["Bachelor", "PhD", "Master", "Bachelor", "Bachelor", 
                               "High School", "High School", "High School", "Bachelor", "Bachelor"],
    "Group X": [2, 3, 3, 2, 2, 1, 1, 1, 2, 2],
    "Wealth": [18.1e9, 900000, 10000, 25000, 40000, 12500, 29000, 1500, 125000, 100000],
    "Group Y": [3, 2, 1, 1, 2, 1, 1, 1, 2, 2]
}

df = pd.DataFrame(data)

In [2]:
display(df)

   ID     Name Academic Qualification  Group X        Wealth  Group Y
0   1    Alice               Bachelor        2  1.810000e+10        3
1   2      Bob                    PhD        3  9.000000e+05        2
2   3  Charlie                 Master        3  1.000000e+04        1
3   4    David               Bachelor        2  2.500000e+04        1
4   5     Emma               Bachelor        2  4.000000e+04        2
5   6    Frank            High School        1  1.250000e+04        1
6   7    Grace            High School        1  2.900000e+04        1
7   8    Henry            High School        1  1.500000e+03        1
8   9      Ivy               Bachelor        2  1.250000e+05        2
9  10     Jack               Bachelor        2  1.000000e+05        2

In [3]:
# Count total individuals
total_individuals = len(df)

# Count individuals with a Bachelor's degree
bachelor_group = df[df["Group X"] == 2]
count_bachelor = len(bachelor_group)

# Count super wealthy individuals (Wealth Group Y = 3)
super_wealthy = df[df["Group Y"] == 3]
count_super_wealthy = len(super_wealthy)

# Count individuals who are both super wealthy and have a Bachelor's degree
super_wealthy_bachelor = bachelor_group[bachelor_group["Group Y"] == 3]
count_super_wealthy_bachelor = len(super_wealthy_bachelor)

# Calculate P(A | B)
P_A_given_B = count_super_wealthy_bachelor / count_bachelor
print(f"P(Super Wealthy | Bachelor's Degree) = {P_A_given_B:.2f}")

P(Super Wealthy | Bachelor's Degree) = 0.20

In [4]:
# Given probabilities
P_A = 0.6  # Probability that a chip comes from Machine A
P_B = 0.4  # Probability that a chip comes from Machine B

P_D_given_A = 0.02  # Probability of defect given Machine A
P_D_given_B = 0.05  # Probability of defect given Machine B

# Compute total probability of a defective chip using Law of Total Probability
P_D = (P_D_given_A * P_A) + (P_D_given_B * P_B)

print(f"P(D) = {P_D:.4f}")

# Compute P(B | D) using Bayes' Theorem
P_B_given_D = (P_D_given_B * P_B) / P_D

print(f"P(Machine B | Defective Chip) = {P_B_given_D:.3f}")

P(D) = 0.0320
P(Machine B | Defective Chip) = 0.625

In [3]:
import pandas as pd
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Load the dataset
dataset_dict = {
    'Outlook': ['sunny', 'sunny', 'overcast', 'rainy', 'rainy', 'rainy', 'overcast', 'sunny', 'sunny', 'rainy', 'sunny', 'overcast', 'overcast', 'rainy', 'sunny', 'overcast', 'rainy', 'sunny', 'sunny', 'rainy', 'overcast', 'rainy', 'sunny', 'overcast', 'sunny', 'overcast', 'rainy', 'overcast'],
    'Temperature': [85.0, 80.0, 83.0, 70.0, 68.0, 65.0, 64.0, 72.0, 69.0, 75.0, 75.0, 72.0, 81.0, 71.0, 81.0, 74.0, 76.0, 78.0, 82.0, 67.0, 85.0, 73.0, 88.0, 77.0, 79.0, 80.0, 66.0, 84.0],
    'Humidity': [85.0, 90.0, 78.0, 96.0, 80.0, 70.0, 65.0, 95.0, 70.0, 80.0, 70.0, 90.0, 75.0, 80.0, 88.0, 92.0, 85.0, 75.0, 92.0, 90.0, 85.0, 88.0, 65.0, 70.0, 60.0, 95.0, 70.0, 78.0],
    'Wind': [False, True, False, False, False, True, True, False, False, False, True, True, False, True, True, False, False, True, False, True, True, False, True, False, False, True, False, False],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(dataset_dict)

# Prepare data for model
df = pd.get_dummies(df, columns=['Outlook'],  prefix='', prefix_sep='', dtype=int)
df['Wind'] = df['Wind'].astype(int)
df['Play'] = (df['Play'] == 'Yes').astype(int)

# Split data into training and testing sets
X, y = df.drop(columns='Play'), df['Play']
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.5, shuffle=False)

# Scale numerical features (for automatic binarization)
scaler = StandardScaler()
float_cols = X_train.select_dtypes(include=['float64']).columns
X_train[float_cols] = scaler.fit_transform(X_train[float_cols])
X_test[float_cols] = scaler.transform(X_test[float_cols])

# Train the model
nb_clf = BernoulliNB()
nb_clf.fit(X_train, y_train)

# Make predictions
y_pred = nb_clf.predict(X_test)

# Check accuracy
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

Accuracy: 0.8571428571428571